// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220104212616_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Domain.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("772ea05b-f021-489c-8f2f-6bc33ab7b527"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2021, 11, 4, 23, 26, 15, 953, DateTimeKind.Local).AddTicks(8929),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("c61a356b-7a34-4c6c-a8ec-217f39968f4b"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2021, 12, 4, 23, 26, 15, 955, DateTimeKind.Local).AddTicks(9677),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("5a8381ca-bbfc-4cbe-af63-16defad363e6"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2022, 2, 4, 23, 26, 15, 955, DateTimeKind.Local).AddTicks(9704),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("bb66bd39-e534-482c-a42a-cbe834eb166a"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 3, 4, 23, 26, 15, 955, DateTimeKind.Local).AddTicks(9709),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("5c48f595-d176-4276-9222-e83de6b0e0fe"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 4, 4, 23, 26, 15, 955, DateTimeKind.Local).AddTicks(9713),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("32d0828f-842a-41f7-830e-3a92bc56458e"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 5, 4, 23, 26, 15, 955, DateTimeKind.Local).AddTicks(9716),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("9ca1d5e3-c6d0-40f3-a08e-de219611e802"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 6, 4, 23, 26, 15, 955, DateTimeKind.Local).AddTicks(9720),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("64f93cc3-53a3-4403-be3c-b5fe7b11852b"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 7, 4, 23, 26, 15, 955, DateTimeKind.Local).AddTicks(9739),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("73627b0b-2983-4504-9e00-606378c463a0"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2022, 8, 4, 23, 26, 15, 955, DateTimeKind.Local).AddTicks(9742),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("3d10812b-eb2f-47d6-b6d0-21ae094a30bd"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2022, 9, 4, 23, 26, 15, 955, DateTimeKind.Local).AddTicks(9745),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
